#!/usr/bin/env bash
# The current repo root
CURRENT_REPO=$(git rev-parse --show-toplevel)
if [[ -f $CURRENT_REPO/.gitlfs ]]; then
  command -v git-lfs > /dev/null 2>&1 || {
    echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"
    exit 2
  }
  git lfs post-checkout "$@"
fi
