FROM photon:3.0

# Install dependencies
RUN tdnf upgrade -y && tdnf remove toybox -y && \
    tdnf install -y build-essential git rpm-build coreutils util-linux \
    make autoconf automake gcc ncurses-devel sed tar texinfo procps-ng grep \
    findutils gzip file which libxml2 python3 python3-pip jq && \
    pip3 install --upgrade pip && pip3 install setuptools && \
    pip3 install demjson

COPY .  /root
WORKDIR /root
