name: docker-compose-test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t slimm609/checksec:latest .
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: slimm609/checksec:latest
